name: Test scheduler GitHub

on:
  schedule:
    - cron: "13,28,43,58 * * * *"
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Afficher l'heure
        run: date -u
